### ISSUE TITLE
Problem with Cyrillic titles

### ISSUE THREAD

**Issue by msenin** [sonata-project/SonataNewsBundle#114]
It's not possible to give Cyrillic title for post, category or tag.

The problem in 

in vendor\sonata-project\news-bundle\Sonata\NewsBundle\Model\Tag.php at line 139  
        // transliterate
        if (function_exists('iconv')) {
            $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        }

Explanation of problem is here: http://stackoverflow.com/questions/11915330/iconv-notice-iconv-function-iconv-detected-an-illegal-character-in-input

It will be better to use https://github.com/jbroadway/urlify instead of http://snipplr.com/view/22741/slugify-a-string-in-php/ for slugify() method.

**Comment by maectpo** [comment]
Do you have any solution for the problem?

**Comment by dim07** [comment]
You can override public functions as me 
https://github.com/dim07/demi/commit/6c4a560aac24ebab858a31efd104600c4e09fbce

**Comment by core23** [comment]
Can you provide a PR? @dim07

**Comment by jordisala1991** [comment]
Closing this one as this is not a problem anymore (or if it is, not ours)

Tag.php was moved to ClassificationBundle, and after some time, the code you mention was replaced by cocur/slugify, which probably don't have the issue you mention.

https://github.com/sonata-project/SonataClassificationBundle/pull/229
