### ISSUE TITLE
Incompatibility with Oracle

### ISSUE THREAD

**Issue by laherreria** [sonata-project/SonataNewsBundle#118]
I just installed this bundle and when I try to execute the /news/archive route using Oracle as database, I get this error:
```
ORA-01791: not a SELECTed expression") in SonataNewsBundle:Post:archive.html.twig at line 17. 
```

This is the query (generated by Doctrine) which causes the error:
```
SELECT DISTINCT n0_.id AS ID0
FROM news__post n0_
LEFT JOIN news__post_tag n2_ ON n0_.id = n2_.post_id
LEFT JOIN news__tag n1_ ON n1_.id = n2_.tag_id AND (n1_.enabled = 1)
LEFT JOIN fos_user_user f3_ ON n0_.author_id = f3_.id AND (f3_.enabled = 1)
WHERE n0_.enabled = ?
ORDER BY n0_.publication_date_start DESC
```

It seems like Oracle doesn't like the combination of ORDER BY and DISTINCT. This is a description of this error code I found on the internet:
"The query is a SELECT DISTINCT query with an ORDER BY clause. In this context, all ORDER BY items must be constants, SELECT list expressions, or expressions whose operands are constants or SELECT list expressions."

**Comment by core23** [comment]
I think this is an issue in doctrine.
