### ISSUE TITLE
Category: getPosts not working

### ISSUE THREAD

**Issue by AlexandreKilian** [sonata-project/SonataNewsBundle#125]
Hello!
After fighting with this for a while with the Category Entity/Model, i found out that finding **Posts** of a **Category** with *Category->getPosts()* does not work. Finding Posts via the **PostManager** works if you add the **Category** as Parameter, but finding posts via the **Category** returns always *null*

**Comment by core23** [comment]
The category entity was moved to the **SonataClassificationBundle**. There is no inverse dependency to a post.
