### ISSUE TITLE
Can't publish posts - Cannot set Comment default status

### ISSUE THREAD

**Issue by jernejpangersic** [sonata-project/SonataNewsBundle#127]
Hi!

When I'm trying to publish a post, I get stopped by an error that Comment default status * cannot be left blank.
The options (Comment default status) appear as list, with elements moderate, invalid, valid. I can't set anything, and I can't publish. 

Can anyone help?
Thanks!

**Comment by core23** [comment]
I'll close this for now. If you have more information for us, you can reopen this.
