### ISSUE TITLE
The options "expanded", "multiple" do not exist

### ISSUE THREAD

**Issue by inrobin** [sonata-project/SonataNewsBundle#131]
symfony/symfony 2.3.4
sonata-project/admin-bundle 2.2.x-dev
sonata-project/news-bundle 2.3.x-dev

In the admin on /sonata/news/post/list page gettings an error:

 The options "expanded", "multiple" do not exist. Known options are: "action", "attr", "auto_initialize", "block_name", "by_reference", "cascade_validation", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_provider", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "inherit_data", "intention", "invalid_message", "invalid_message_parameters", "label", "label_attr", "mapped", "max_length", "method", "pattern", "post_max_size_message", "property_path", "read_only", "required", "sonata_admin", "sonata_field_description", "translation_domain", "trim", "validation_groups", "virtual"
500 Internal Server Error - InvalidOptionsException 

If I comment out #122 line
in https://github.com/sonata-project/SonataNewsBundle/blob/master/Admin/PostAdmin.php:
->add('tags', null, array('field_options' => array('expanded' => true, 'multiple' => true)))

it works.

**Comment by core23** [comment]
Already fixed
