### ISSUE TITLE
API development status

### ISSUE THREAD

**Issue by grosenbaum** [sonata-project/SonataNewsBundle#197]
Here is the todo list for the posts part of the Sonata API:
## Global
- [x] Remove the _HTML_ _format of the Requirements for each HTTP METHOD - sonata-project/SonataNewsBundle/pull/200
- ~~Fix the problem with provided params always overrided by default values~~ (see sonata-project/SonataCoreBundle#67)
## POSTS
- [x] Complete missing descriptions - sonata-project/SonataNewsBundle/pull/196
### GET /api/news/posts.{_format}
- [x] Activate the pagination and the count by page
- [x] Fix missing tags for each post retrieved - sonata-project/SonataNewsBundle/pull/199
- [x] Fix "Pager may not return expected number of results when leftJoin are used" - sonata-project/SonataDatagridBundle#4
### POST /api/news/posts.{_format}
- [x] Sending a wrong contentFormatter value should not trigger a 500 error - sonata-project/SonataNewsBundle/pull/204
- [x] Sending an empty slug should not trigger a 500 error - sonata-project/SonataNewsBundle/pull/204
### PUT /api/news/posts/{id}.{_format}
- [x] Sending an empty contentFormatter should not trigger a 500 error - sonata-project/SonataNewsBundle/pull/204
### GET /api/news/posts/{id}.{_format}
- [x] A modified post with PUT cannot be displayed (#198) - sonata-project/SonataNewsBundle/pull/205
### GET      /api/news/posts/{id}/comments.{_format}
- [x] Return comment status in serialized comments response - sonata-project/SonataNewsBundle/pull/201
### POST /api/news/posts/{id}/comments.{_format}
- [x] Modify description for 400/403 errors - sonata-project/SonataNewsBundle/pull/196
- [x] Wrong error returned when tempting to POST a comment to a post that has _comment_enabled_ = _false_
- [x] Only allow defined comment status to be set - sonata-project/SonataNewsBundle/pull/204
### Behat tests
- [x] Add the Behat test for GET - sonata-project/sandbox/pull/379
- [x] Optimize the Behat tests for PUT - sonata-project/sandbox/pull/379
- [x] Optimize the Behat tests for DELETE - sonata-project/sandbox/pull/379
### GET / PUT / DELETE /api/news/comments/{id}
- [x] Complete missing descriptions - sonata-project/SonataNewsBundle/pull/196
### Behat tests
- [x] Add the Behat test for GET - sonata-project/sandbox/pull/379
- [x] Optimize the Behat tests for PUT - sonata-project/sandbox/pull/379
- [x] Optimize the Behat tests for DELETE - sonata-project/sandbox/pull/379

Feel free to complete the todo list.

**Comment by jordisala1991** [comment]
Everything is checked. Lets close this
