### ISSUE TITLE
No CkEditor in SonataNewsBundle

### ISSUE THREAD

**Issue by emmanuel-tesson** [sonata-project/SonataNewsBundle#211]
Hi
i just installed the SonataNewsBundle, and with the default configuration (installation instruction), i do not have any wysiwyg editor in SonataAdminBundle for post content ?

my versions of 
SonataNewsBundle : 2.3.4
SonataAdminBundle : dev-master

i checked some forum and i discovered that there are some differences in Admin/PostAdmin between my release and the last one : 

my version

->add('content', 'sonata_formatter_type', array(
                    'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
                    'format_field'   => 'contentFormatter',
                    'source_field'   => 'rawContent',
                    'source_field_options'      => array(
                        'attr' => array('class' => 'span10', 'rows' => 20)
                    ),
                    'target_field'   => 'content',
                    'listener'       => true,
                ))

the last : 
->add('content', 'sonata_formatter_type', array(
                    'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
                    'format_field'   => 'contentFormatter',
                    'source_field'   => 'rawContent',
                    'source_field_options'      => array(
                        'horizontal_input_wrapper_class' => $this->getConfigurationPool()->getOption('form_type') == 'horizontal' ? 'col-lg-12': '',
                        'attr' => array('class' => $this->getConfigurationPool()->getOption('form_type') == 'horizontal' ? 'span10 col-sm-10 col-md-10': '', 'rows' => 20)
                    ),
                    'ckeditor_context'     => 'news',
                    'target_field'   => 'content',
                    'listener'       => true,
                ))

but after edited the code, i did not find any change...

I think i have a problem with the ckeditor_context configuration

if someone could help me ..??

**Comment by deafboy2k9** [comment]
@emmanuel-tesson Did you check out http://sonata-project.org/bundles/formatter/master/doc/reference/formatter_widget.html?

You need to register the form layout with twig for it to work.

**Comment by sagikazarmark** [comment]
Do you have the formatter bundle installed?

**Comment by jordisala1991** [comment]
Old issue and seems like a configuration problem so closing. Ping me if this is still an issue

**Comment by timoberlin** [comment]
We've installed Sonata Formatter and Sonata News. The CKEditor configuration "news" is missing when I want to post a new news article. I've checked the whole documentation of Sonata but I wasn't able to find this configuration. I would be very happy if I could get help.
