### ISSUE TITLE
Breadcrumb render

### ISSUE THREAD

**Issue by cassianotartari** [sonata-project/SonataNewsBundle#222]
I'm digging into Sonata's code to figure out why of the error that is mentioned here too: https://groups.google.com/d/msg/sonata-users/e5nfitfm02A/KqoWtOqSAPsJ

```
ERROR - [cms::blockContext] block.id=545 - error while resolving options - The options "context", "post" do not exist. Known options are: "attr", "cache_policy", "children_class", "current_class", "current_uri", "extra_cache_keys", "first_class", "include_homepage_link", "last_class", "menu_class", "menu_name", "menu_template", "safe_labels", "template", "title", "ttl", "use_cache" 
```

It is fired by the template call in ``SonataNewsBundle:Post:view.html.twig``
```twig
{{ sonata_block_render_event('breadcrumb', { 'context': 'news_post', 'post': post, 'current_uri': app.request.requestUri }) }}
```

The error is registered in ``SonotaBlockBundle/Block/BlockContextManager.php`` in the ``catch`` of
```php
$settings = $optionsResolver->resolve(array_merge($block->getSettings(), $settings));
```

This is not exactly an error because breadcrumb is correctly rendered but logger shows as a error and I receive an email each time...

Maybe is something related to ``sonata_block`` in ``config.yml`` like is saying here: https://github.com/sonata-project/SonataBlockBundle/blob/master/UPGRADE-2.2.md but I'm not using SonataPageBundle, just news bundle to render a little blog.

Thanks.

**Comment by core23** [comment]
This go fixed some time ago https://github.com/sonata-project/SonataSeoBundle/pull/99
