### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by maikelohcfg** [sonata-project/SonataNewsBundle#224]
When i try from sonata admin to create new post for sonata news i get this error

Serialization of 'Closure' is not allowed

I am working with symfony 2.6.1 and sonata news in my composer.json is this "sonata-project/news-bundle": "dev-master",

**Comment by joizjonas** [comment]
it looks like fixed. thanks

**Comment by rande** [comment]
The issue was fixed in the SonataFormatterBundle.
