### ISSUE TITLE
Wrong queries generated for pdo_pgsql

### ISSUE THREAD

**Issue by ceochronos** [sonata-project/SonataNewsBundle#226]
Hi all,

This is related to Issue #65. According to issue #65 only affects PostgresSQL. At the time of this writing http://demo.sonata-project.org/ was not available for login and testing.

After installing and configuring `sonata-project/SonataNewsBundle` and creating the first post. When I try to access it, `/news/2014/12/28/hello-world`, I get this exception

```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT count(DISTINCT n0_.id) AS sclr0 FROM news__comment n0_ WHERE n0_.status = ? AND n0_.post_id = ? ORDER BY n0_.created_at DESC' with params [1, 1]:

SQLSTATE[42803]: Grouping error: 7 ERROR: column "n0_.created_at" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...ERE n0_.status = $1 AND n0_.post_id = $2 ORDER BY n0_.create...
^") in SonataNewsBundle:Post:view.html.twig at line 60.
```

I was able to track the error to `sonata-project/SonataDatagridBundle` which means this error could affect all others bundles that depend on it: Classification, News and Page (according to theirs composer.json files)

Actually, there are two errors:

## 1. Sonata\DatagridBundle\Pager\Doctrine\Pager

https://github.com/sonata-project/SonataDatagridBundle/blob/master/Pager/Doctrine/Pager.php#L39-L41

### Program flow

* The url `/news/2014/12/28/hello-world` matches the route `sonata_news_view`.
* The route `sonata_news_view` executes the action `Sonata\NewsBundle\Controller\PostController::viewAction`
* The action `Sonata\NewsBundle\Controller\PostController::viewAction` renders the view `SonataNewsBundle:Post:view.html.twig`
* The view `SonataNewsBundle:Post:view.html.twig` includes the action `SonataNewsBundle:Post:comments`
* The action `SonataNewsBundle:Post:comments` defines a `$pager` variable via https://github.com/sonata-project/SonataNewsBundle/blob/master/Entity/CommentManager.php#L94-L126.
Note Line 102 which define a `$query` variable, line 119 which define a `$pager` variable of  `Sonata\DatagridBundle\Pager\Doctrine\Pager` and line 123 which calls `init()` method on `$pager` variable.

### Description

On https://github.com/sonata-project/SonataNewsBundle/blob/master/Entity/CommentManager.php#L102-L104 is created a `$query` in order to get the comments ordered by the column `created_at`. A clone of this `$query` is used in https://github.com/sonata-project/SonataDatagridBundle/blob/master/Pager/Doctrine/Pager.php#L31-L42 to count the comments of the current post.

Before L39 the query is

```php
echo $countQuery->getQueryBuilder()->getQuery()->getSQL();
```
```sql
SELECT n0_.name AS name0, n0_.url AS url1, n0_.email AS email2, n0_.message AS message3, n0_.status AS status4, n0_.created_at AS created_at5, n0_.updated_at AS updated_at6, n0_.id AS id7, n0_.post_id AS post_id8 
FROM news__comment n0_ 
WHERE n0_.status = ? AND n0_.post_id = ? 
ORDER BY n0_.created_at DESC
```

After L39 the query is

```php
echo $countQuery->getQueryBuilder()->getQuery()->getSQL();
```
```sql
SELECT count(DISTINCT n0_.id) AS sclr0 
FROM news__comment n0_ 
WHERE n0_.status = ? AND n0_.post_id = ? 
ORDER BY n0_.created_at DESC
```
Before L39 the query is valid, after L39 is not.

### Solution

Given the use case I started analyzing, see `Program flow`, one possible solution is:

https://github.com/ceochronos/SonataDatagridBundle/commit/3f09aed036611fbf5e4295fc293fa404958078fe?diff=split

```php
$dqlParts = $countQuery->getQueryBuilder()->getDQLParts();
if (count($dqlParts['orderBy']) && !count($dqlParts['groupBy']))
{
    $countQuery->getQueryBuilder()->resetDQLPart('orderBy');
}
```

In other words, if there is a `order by` clause and not a `group by` clause, remove the `order by` clause in order to keep the `$query` valid.

This works for the `Program flow` I analyzed. I am confident this will work with the other use cases in  `sonata-project/SonataNewsBundle`. However, I am not sure how this will work with the other bundles that depend on `sonata-project/SonataDatagridBundle`.

Also, note that this solution removes the `order by` clause which, in a general scenario, may lead to return wrong information. However, since the next line, L47, is a call to `getSingleScalarResult()` I think is safe to assume that the original `$query` was intended to return only one tuple. So removing the `order by` clause does not break anything else.

## 2. Sonata\DatagridBundle\ProxyQuery\Doctrine

https://github.com/sonata-project/SonataDatagridBundle/blob/master/ProxyQuery/Doctrine/ProxyQuery.php#L58-L108

### Program flow

* After fixing error 1
* The action `SonataNewsBundle:Post:comments` renders the view `SonataNewsBundle:Post:comments.html.twig`
* On view `SonataNewsBundle:Post:comments.html.twig` the method `getResults()` is called on `$pager` variable.
* `$pager->getResults()` calls `Sonata\DatagridBundle\ProxyQuery\Doctrine\ProxyQuery:execute()`
* `Sonata\DatagridBundle\ProxyQuery\Doctrine\ProxyQuery:execute()` calls `Sonata\DatagridBundle\ProxyQuery\Doctrine\ProxyQuery:getFixedQueryBuilder()`

### Description

Do not fully understand this method. First executes a cloned `$query` in order to rewrite the `$query` and execute it once again(?).

### Solution

Given the use case I started analyzing, see `Program flow`, one possible solution is:

https://github.com/ceochronos/SonataDatagridBundle/commit/80fa9034c1ec688f72ad7a3450bce0d417dc3126?diff=split

```php
$dqlParts = $queryBuilderId->getDQLParts();
if (count($dqlParts['orderBy']) && !count($dqlParts['groupBy']))
{
    $queryBuilderId->resetDQLPart('orderBy');
}
```

In other words, if there is a `order by` clause and not a `group by` clause, remove the `order by` clause in order to keep the `$query` valid.

This works for the `Program flow` I analyzed. However, I am not sure how this will work with the other bundles that depend on `sonata-project/SonataDatagridBundle` or the other use cases in  `sonata-project/SonataNewsBundle`.

Also, note that this solution removes the `order by` clause which, in a general scenario, may lead to return wrong information. However, even though I do not fully the method `Sonata\DatagridBundle\ProxyQuery\Doctrine\ProxyQuery:getFixedQueryBuilder()`, removing the `order by` clause from the cloned `$query` which is used to rewrite the `$query` and then execute it once again does not affect the final result.

So removing the `order by` clause from `$queryBuilderId` but not from `$queryBuilder` does not break anything else.

\cc @pajooh, @danigonza, @idhard, @clovis818

**Comment by afurculita** [comment]
+1

**Comment by jaroslavas** [comment]
Thanks @ceochronos , you fixes seem to be working.

**Comment by core23** [comment]
Can you verify this @ceochronos

**Comment by ceochronos** [comment]
I'm sorry @core23 I'm not working on this (or with symfony) anymore

**Comment by core23** [comment]
@jaroslavas Can you verify this issue?

**Comment by jaroslavas** [comment]
Yep, there was a problem that I had to fix by myself. Here is my fork's branch with a fix: https://github.com/jaroslavas/SonataDatagridBundle/tree/postgre-fix

**Comment by core23** [comment]
I'll close this for now. Please supply a new PR for the fix @jaroslavas
