### ISSUE TITLE
Dependency on SEO Bundle

### ISSUE THREAD

**Issue by na-ji** [sonata-project/SonataNewsBundle#237]
Hello !

I have a question : is there a dependency on seo-bundle ? Because I don't see any in the composer.json nor in the documentation. 
However, in the file [SonataNewsBundle/Block/Breadcrumb/BaseNewsBreadcrumbBlockService.php](https://github.com/sonata-project/SonataNewsBundle/blob/master/Block/Breadcrumb/BaseNewsBreadcrumbBlockService.php) there is an include of a seo-bundle file. 

Thank you for your help !

**Comment by rande** [comment]
It is an optional dependency.
