### ISSUE TITLE
Fix deprecated settings method on block service

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataNewsBundle#247]
To be done when https://github.com/sonata-project/SonataBlockBundle/pull/204 will be merged.

**Comment by sagikazarmark** [comment]
It is done :wink:

**Comment by OskarStark** [comment]
you are right @sagikazarmark 

ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
@sagikazarmark @OskarStark Nope.

See this as example: https://github.com/sonata-project/SonataNewsBundle/blob/68a5a2308827990b7bb29a59b62a3a5dac562bcd/Block/RecentCommentsBlockService.php#L110

But feel free to fix it on PR if you're hurry. ;-)

**Comment by sagikazarmark** [comment]
Ah, sorry. I just noticed the PR is merged.

**Comment by OskarStark** [comment]
me too... sorry :smile:

**Comment by sagikazarmark** [comment]
PR pushed
