### ISSUE TITLE
CHANGELOG.md or CHANGELOG.txt file

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataNewsBundle#260]
Is there a reason, why there are different Changelog files?

``TXT`` files
https://github.com/sonata-project/SonataNewsBundle/blob/master/CHANGELOG.txt
https://github.com/sonata-project/SonataUserBundle/blob/master/CHANGELOG.txt

``MD`` files
https://github.com/sonata-project/SonataAdminBundle/blob/master/CHANGELOG.md
any other sonata repo

Both files :confused:
https://github.com/sonata-project/SonataClassificationBundle/blob/master/CHANGELOG.txt
https://github.com/sonata-project/SonataClassificationBundle/blob/master/CHANGELOG.md

**Comment by Soullivaneuh** [comment]
That's a good question. Surely a historical one.

cc @rande. :-)

**Comment by rande** [comment]
:facepunch: go for markdown ;)

**Comment by OskarStark** [comment]
:+1:

**Comment by sagikazarmark** [comment]
See #262, sonata-project/SonataUserBundle#625, sonata-project/SonataClassificationBundle#140

**Comment by sagikazarmark** [comment]
All PRs merged, this can be closed
