### ISSUE TITLE
renderArchive type mismatch

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataNewsBundle#271]
Catchable Fatal Error: Argument 1 passed to Sonata\NewsBundle\Controller\PostController::renderArchive() must be of the type array, object given

Error encountered when using the sonata 2.4 develop sandbox

**Comment by OskarStark** [comment]
any news @stphnpt

**Comment by stphnpt** [comment]
@OskarStark No good news on the news bundle ! I didn't have time to check root cause but still no change after latest composer update:

Catchable Fatal Error: must be of the type array, object given
called in /vendor/sonata-project/news-bundle/Controller/PostController.php on line 76 and defined in /vendor/sonata-project/news-bundle/Controller/PostController.php at line 40

**Comment by OskarStark** [comment]
Does #274 fixes your problem? @stphnpt

**Comment by stphnpt** [comment]
@OskarStark Yes ! works like a charm. thanks.

**Comment by OskarStark** [comment]
:+1:
