### ISSUE TITLE
  Bundle "ApplicationSonataNewsBundle" does not exist or it is not enabled. 

### ISSUE THREAD

**Issue by anboo** [sonata-project/SonataNewsBundle#272]
php app/console sonata:easy-extends:generate SonataNewsBundle -d src
Returned me:
  [InvalidArgumentException]                                                 
  Bundle "ApplicationSonataNewsBundle" does not exist or it is not enabled.

class Application\Sonata\NewsBundle\ApplicationSonataNewsBundle() not found!

**Comment by Neodork** [comment]
If you're experiencing this following this tutorial:
https://sonata-project.org/bundles/news/2-2/doc/reference/installation.html

You should make sure you comment ApplicationSonataNewsBundle in the config before running the command.

```php
doctrine:
    orm:
        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
                mappings:
                    #ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~
```

**Comment by OskarStark** [comment]
:+1:

**Comment by OskarStark** [comment]
@anboo , if this fixes you rproblem a PR for the Docs would be appreciated

**Comment by bizmate** [comment]
looks like this could be closed

**Comment by greg0ire** [comment]
Right, good catch!
