### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ymdomenech** [sonata-project/SonataNewsBundle#280]
Problem 1
    - Installation request for sonata-project/news-bundle dev-master -> satisfiable by sonata-project/news-bundle[dev-master].
    - sonata-project/news-bundle dev-master requires sonata-project/datagrid-bundle ~2.2 -> no matching package found.

That version doesnt exist.
I fixed that problem with:

"sonata-project/datagrid-bundle": "dev-master",
in my composer.json

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
