### ISSUE TITLE
Newsbundle incompatible with Admin 3.X

### ISSUE THREAD

**Issue by sujayjaju** [sonata-project/SonataNewsBundle#301]
Trying to install newsbundle (dev-master) with "sonata-project/admin-bundle" 3.X-dev does not work. Newsbundle is dependent on admin 2.3.x

**Comment by Th3Mouk** [comment]
The work is in progress, there is many bundle to configure with new workflow see here : https://github.com/sonata-project/SonataAdminBundle/issues/3731

**Comment by sujayjaju** [comment]
Thanks for replying.
Unfortunately my dependencies are broken during the flux period and I cannot go back to the original state as well.

UserBundle dev no longer works with 2.3 and NewBundle only works with 2.3. Any idea on when this would be addressed?

**Comment by Soullivaneuh** [comment]
@sujayjaju You can use require alias: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

Something like `"sonata-project/admin-bundle": "3.x-dev as 2.3"` should do the trick.

Please tell us if this solve your issue.

**Comment by Th3Mouk** [comment]
You can use temporaly this dependency : https://github.com/Th3Mouk/CMSCoreBundle/blob/1.2-dev/composer.json#L19

My production is based on stable 2.3 versions.

**Comment by sujayjaju** [comment]
Thanks for the suggestions. The alias did not quite work: in my case I need to use the latest admin and user bundles - so I ended up creating VCS alias. Now I am stuck on:

> sonata-project/news-bundle 3.x-dev requires sonata-project/classification-bundle 3.x-dev@dev -> satisfiable by sonata-project/classification-bundle[3.x-dev] but these conflict with your r
> equirements or minimum-stability

This is what I did:

- [ ] Forked the repos and updated compser.json in new 3.x branches in each
- [ ] Updated my projects composer.json

```
   "repositories":
    [
        {
            "type": "vcs",
            "url": "https://github.com/sujayjaju/SonataNewsBundle"
        },
        {
            "type": "vcs",
            "url": "https://github.com/sujayjaju/SonataFormatterBundle"
        },
        {
            "type": "vcs",
            "url": "https://github.com/sujayjaju/SonataMediaBundle"
        },
        {
            "type": "vcs",
            "url": "https://github.com/sujayjaju/SonataClassificationBundle"
        }
    ],
    "require": {
        ...
        "sonata-project/admin-bundle": "3.x-dev",
        "sonata-project/doctrine-orm-admin-bundle": "3.x-dev",
        "sonata-project/user-bundle": "3.x-dev",

        "sonata-project/formatter-bundle": "3.x-dev",
        "sonata-project/news-bundle": "3.x-dev",
        "sonata-project/media-bundle": "3.x-dev",
         ...
    },

```

Any idea what am I missing

**Comment by sujayjaju** [comment]
Added
`   "sonata-project/classification-bundle": "3.x-dev",`
to my composer.json to make it work.

Its ugly - but at least it works.

**Comment by jordisala1991** [comment]
I think this is outdated. Now we should be compatible with admin-bundle 3
