### ISSUE TITLE
Unable to add a new attribute in the comment form without variable reference

### ISSUE THREAD

**Issue by vihuvac** [sonata-project/SonataNewsBundle#331]
I am currently trying to add a [recaptcha](https://github.com/vihuvac/recaptcha-bundle) field inside the comment form, I am following the official doc of [How to Override any Part of a Bundle](http://symfony.com/doc/2.8/cookbook/bundles/override.html) but I get this error:

``` md
Neither the property "recaptcha" nor one of the methods "recaptcha()", "getrecaptcha()"/"isrecaptcha()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView" in SonataNewsBundle:Post:comment_form.html.twig at line 36
```

I am overriding the SonataNewsBundle:Post:comment_form.html.twig file in order to add the recaptcha widget, this is the block where I get the error:

``` twig
{{ form_label(form.recaptcha, null, { "label_attr": { "class": "col-sm-3 control-label" } }) }}
<div class="col-sm-5">
    {% form_theme form "VihuvacRecaptchaBundle:Form:vihuvac_recaptcha_widget.html.twig" %}
    {{ form_widget(form.recaptcha) }}
</div>
```

> **Note**:
> 
> It does not happen if I override straight the form file **CommentType** located at: `vendor/sonta-project/SonataNewsBundle/Form/Type/CommentType.php`.

Do I have to bear in mind any additional resource in order to implement this feature? Maybe I can integrate this feature in the official bundle **SonataNewsBundle** and create a pull request, as long as you guys have not any problem of course!

**Comment by jordisala1991** [comment]
You probably need to atleast add the recaptcha on the CommentType.

Closing for now, if you still having this issue, please ping me to reopen.
