### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by artursvonda** [sonata-project/SonataNewsBundle#348]
Is anyone working on Symfony 3.x support?

**Comment by greg0ire** [comment]
I don't think so. Would you like to?

**Comment by artursvonda** [comment]
Could try. What versions should the update support? Currently news bundle supports ^2.3. Should we drop older versions and just support ^2.7 to make things easier? Or even ^2.8.

**Comment by greg0ire** [comment]
Dropping support for versions is considered a BC-break,  and should be done on the master branch, in a separate PR. If you want to give this a try, make a PR allowing sf 3, and Travis should show what needs to be done if this bundle is well covered. This PR should be done on 3.x, in a BC manner. Most of the Sonata bundles are already compatible, so you can have a look at them if you need to know how to do things in a way that works with both versions. Thanks a lot!

**Comment by jordisala1991** [comment]
We are compatible with Symfony 3 and 4. If you see any problem here, post a more specific issue
