### ISSUE TITLE
Overriding templates

### ISSUE THREAD

**Issue by ebrost** [sonata-project/SonataNewsBundle#349]
In RecentsPostBlockService.php as in PostController viewAction , the reference to the template is hard coded.
Am i missing something or do  i have to extends thoses classes to use my own templates ?
I didn't find any reference in the dows.

Great job by the way !

**Comment by OskarStark** [comment]
Hi @ebrost you could extend the Service class and use the OptionsResolver to configure `template` as you like

**Comment by ebrost** [comment]
thanks @OskarStark . That's why i was going to do but as mentionned on [stackoverflow](https://stackoverflow.com/questions/25898775/symfony2-override-part-of-template-from-third-party-bundle) , you can just put your templates  in `app/Resources/SonataNewsBundle/views/Block/recent_posts.html.twig`

Hope this would help news users of symfony/sonata

**Comment by OskarStark** [comment]
Thanks for the feedback
