### ISSUE TITLE
Unable to Create new Post 

### ISSUE THREAD

**Issue by 5-digits** [sonata-project/SonataNewsBundle#368]
Hi everybody, 
is there any config or installation to do it before to be able create a new post or add category on SonataNewsBundle, because i'm trying to fix this issue & not doc explain
when choose the route ("/news") redirect to ("/news/archive") like the picture below

 any solution please and Thanks for your help!

![newsbundle](https://cloud.githubusercontent.com/assets/6322848/24067514/47e80580-0b7e-11e7-9c1a-4a343e1335f5.PNG)

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
