### ISSUE TITLE
FieldName property "comments_count" makes some trouble

### ISSUE THREAD

**Issue by hpiatkowiak** [sonata-project/SonataNewsBundle#371]
Hi, 

I just want to know if there is a reason why in the schema for mongoDB "Sonata\NewsBundle\Document\BasePost" the definiton for commentsCounts is with underscore instead of camelCase ?
In  `Resources/config/doctrine/BasePost.mongodb.xml` 

`<field name="commentsCount"         type="int"          fieldName="comments_count" default="0"/>`

The issue does not appear to be noticeable yet. However, we now get problems with this setting after an upgrade.

Are there legitimate reasons for this spelling?

**Comment by codebach** [comment]
Top, I am also having a problem with `comments_count` property with mongoDb. 

```
 [Doctrine\ODM\MongoDB\Mapping\MappingException]           
  An error occurred in Sonata\NewsBundle\Document\BasePost
                                
  [ReflectionException]                  
  Property comments_count does not exist     
```

When I change it to `commentsCount` then everything is fine. Can we fix this please? or do you want me to create a PR for this?

**Comment by codebach** [comment]
I will need to fork this bundle to update sonata 3.x. Can you please help me abut this issue?

**Comment by OskarStark** [comment]
@codebach sorry for the late reply, can you please create a PR?

Thank you 👍

**Comment by codebach** [comment]
Thanks for your reply @OskarStark 
Yes, sure I will do it soon.
