### ISSUE TITLE
List of all tags and categories via twig service?

### ISSUE THREAD

**Issue by marcelglaeser** [sonata-project/SonataNewsBundle#375]
Hello,
if there a twig service to render all tags and categories of the blog?
I know `{% for tag in post.tags %}` but its only for the tags of one post.

regards,
Marcel

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
