### ISSUE TITLE
won't meet user-bundle 4.x-dev pulling 3.x-dev issues

### ISSUE THREAD

**Issue by florimond83** [sonata-project/SonataNewsBundle#376]
Hi all,
Working on a fresh install of Synfony 3.2.8 with php: 7.0.18 
Iv'e installed latest available packages for sonata projects as:
#### Sonata packages
> sonata-project/admin-bundle              3.18.2             The missing Symfony Admin Generator
> sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
> sonata-project/cache                     1.0.7              Cache library
> sonata-project/cache-bundle              2.3.1              This bundle provides caching services
> sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
> sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
> sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
> sonata-project/doctrine-orm-admin-bundle 3.1.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
> sonata-project/easy-extends-bundle       2.2.0              Symfony SonataEasyExtendsBundle
> sonata-project/exporter                  1.7.1              Lightweight Exporter library
> sonata-project/notification-bundle       3.1.0              Symfony SonataNotificationBundle
> sonata-project/seo-bundle                2.1.0              Symfony SonataSeoBundle
> sonata-project/user-bundle               dev-master 34a771f Symfony SonataUserBundle

For the latest sona-project/user-bundle I've used the 4.x-dev to get latest FOSUser 2.0 compatibility.
Wanted to now get a 'compatible' package for news-bundle, thus tried 
`composer require sonata-project/news-bundle:4.x-dev`
as requirement for user-bundle are ^3.

Awkward as it seems, when I try, I get errors as if installed package was user-bundle are 3.1...
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - sonata-project/user-bundle 3.x-dev requires friendsofsymfony/user-bundle ^1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7] but these conflict with your requirements or minimum-stability.
>     - sonata-project/news-bundle 4.x-dev requires sonata-project/user-bundle ^3.0 -> satisfiable by sonata-project/user-bundle[3.x-dev].
>     - Installation request for sonata-project/news-bundle 4.x-dev -> satisfiable by sonata-project/news-bundle[4.x-dev].

Can't get around it...Thanks for your reply here.

**Comment by Dunduro** [comment]
you also have the issue of the bundle just not being symfony 3 compatible at the moment
see aswel  #348

**Comment by jordisala1991** [comment]
This can be closed, user-bundle is out, and news-bundle is compatible with it
