### ISSUE TITLE
Not working with Symfony 4

### ISSUE THREAD

**Issue by mishki-svami** [sonata-project/SonataNewsBundle#450]
Hello. 
Will you plan to adopt the bundle for Symfony 4?
Thank you.

**Comment by kunicmarko20** [comment]
Install sonata formatter following https://sonata-project.org/bundles/formatter/3-x/doc/reference/installation.html and then install sonata news.

**Comment by Godfatherlolz** [comment]
Installation can't proceed with Symfony 4 check the docs

**Comment by kunicmarko20** [comment]
@Godfatherlolz I am not sure I understand?

**Comment by Godfatherlolz** [comment]
@kunicmarko20 I am sorry I wasn't clear enough, I followed the doc's Installation process ( It's seems not uptodate with 4.x.x with Flex) there was errors concerning the NameSpace but I got it working. I am not sure if I should flag this as an issue but I get this exception for the Post create
![image](https://user-images.githubusercontent.com/25419445/50155253-ed0a4280-02cb-11e9-8b43-b447fda5038a.png)
and this for comment create
![image](https://user-images.githubusercontent.com/25419445/50155303-0ad7a780-02cc-11e9-9ead-ee462c1f1d47.png)
The latter is a bit understandable.
