### ISSUE TITLE
Drop sonata intl

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataNewsBundle#567]
## Feature Request

The dependency should be dropped and `symfony/intl` respectively `twig/intl-extra` should be used instead.

**Comment by core23** [comment]
There are only two usages:
https://github.com/sonata-project/SonataNewsBundle/blob/3d4df1c66b78700ada404cedfc781d9ababaff66/src/Action/MonthlyPostArchiveAction.php#L40
https://github.com/sonata-project/SonataNewsBundle/blob/3d4df1c66b78700ada404cedfc781d9ababaff66/src/Action/DailyPostArchiveAction.php#L40

This can be replaced with with a symfony [polyfil](https://github.com/symfony/polyfill-intl-icu)

**Comment by phansys** [comment]
Please, note that `sonata-project/intl-bundle` provides more features than the replacements you are proposing.
It allows to detect the timezone and its [locale](https://github.com/sonata-project/SonataIntlBundle/blob/8e2f8c134a6b9b91e333d4d490d3242c9e57303e/src/Timezone/LocaleBasedTimezoneDetector.php#L44-L49) from the [request](https://github.com/sonata-project/SonataIntlBundle/blob/8e2f8c134a6b9b91e333d4d490d3242c9e57303e/src/Locale/RequestDetector.php#L47-L56) and the [authenticated user](https://github.com/sonata-project/SonataIntlBundle/blob/8e2f8c134a6b9b91e333d4d490d3242c9e57303e/src/Timezone/UserBasedTimezoneDetector.php#L36-L63).

**Comment by core23** [comment]
Closing this as this project is abandoned #766
