### ISSUE TITLE
sql error with postgresql

### ISSUE THREAD

**Issue by pajooh** [sonata-project/SonataNewsBundle#65]
i just installed news bundle and trying to view /news/archive route, i get this:

SQLSTATE[42803]: Grouping error: 7 ERROR: column "n0_.publication_date_start" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...enabled = 'true') WHERE n0_.enabled = $1 ORDER BY n0_.public...

i can't trace to the root cause.

**Comment by core23** [comment]
@pajooh Issue still active?

**Comment by jordisala1991** [comment]
Seems like this was already fixed on datagrid-bundle
